### ISSUE TITLE
Amazing project

### ISSUE THREAD

**Issue by LiZhenzhuBlog** [gizatt/dynamic_scene_relighting#1]
Dear Gizatt:

I tend to learn how to projector a 3d sence to a 3d printed model after scan with RGBD.  Did you complete this project? Could you share it in github or privated?
Thanks!

**Comment by gizatt** [comment]
This project has been delayed (covid-related) but I'll be back on it and intend to develop some of the core tools that might be useful to you (RGBD/projector pair calibration) over the next few weeks, with aim to get a working demo by December!

Thanks for the interest!
